---
apiVersion: v1
kind: Service
metadata:
  name: shortify-service
  namespace: shortify
spec:
  type: NodePort
  selector:
    app: shortify
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31010
